#explicitly tells the broker to listen only on the secure port, forces the verification of client certificates, and completely bans anonymous users
listener 8883

# Path to the cryptographic keys (inside the container)
cafile /mosquitto/config/certs/ca.crt
certfile /mosquitto/config/certs/server.crt
keyfile /mosquitto/config/certs/server.key

# THE ARMOR: Reject any connection lacking a valid client certificate signed by your CA
require_certificate true
use_identity_as_username true
allow_anonymous false